name = "ttc-alerts-rss"
main = "worker.js"
compatibility_date = "2026-02-25"

[[kv_namespaces]]
binding = "STATS"
id = "7e1b2f4b956d44e8a4126d8005dd385a"
preview_id = "7e1b2f4b956d44e8a4126d8005dd385a"

[observability]
enabled = true

[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
